name: Echo handson-env

# このワークフローを特定のブランチへのプッシュイベントでトリガーします。
on:
    push:
      branches:
        - main  # 特定のブランチ名に変更する

jobs:
  echo-job:
    runs-on: ubuntu-latest
    env:
      handson-env: You can do it!!

    steps:
    - name: Echo handson_env
      run: echo "handson_env is $handson_env"
